# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'GNewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GNewsApp
  pod 'RxSwift'

  target 'GNewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GNewsAppUITests' do
    # Pods for testing
  end

end
